// src/Repo/DetailPanel/DetailPanel.tsx
import { FullTab, FullTabs } from "@/components/Tabs/FullTabs";
import { qs } from "@/quickStyles";
import { readState } from "@/rxState";
import { state } from "@react-rxjs/core";
import { combineLatest, distinctUntilChanged, filter, map } from "rxjs";
import { Show } from "solid-js";
import * as classes from "./DetailPanel.css";
import { ActiveCommitChanges } from "./ActiveCommitChanges";
import { CommitDetails } from "./CommitDetails";
import { WorkingDirectory } from "./WorkingDirectory";
import { activeCommit$ } from "../RepoGrid/activeCommit";
import { commitLookup$ } from "../repoState";

export const DetailPanel = () => {
  return (
    <FullTabs class={classes.detailPanelContainer}>
      <FullTab header="Working Directory">
        <WorkingDirectory />
      </FullTab>
      <FullTab header="Details">
        <Details />
      </FullTab>
    </FullTabs>
  );
};

const commit$ = state(
  combineLatest([
    activeCommit$.pipe(filter((c) => c !== null)),
    commitLookup$,
  ]).pipe(
    filter(([id, commits]) => id! in commits),
    map(([id, commits]) => commits[id!].commit),
    distinctUntilChanged()
  )
);

const Details = () => {
  const commit = readState(commit$, null);

  return (
    <Show when={commit()}>
      <div class={qs("boxFill", "verticalFlex", "noOverflow")}>
        <CommitDetails commit={commit()!} />
        <ActiveCommitChanges />
      </div>
    </Show>
  );
};

// src/Repo/DetailPanel/DetailPanel.svelte
<script lang="ts">
  import FullTabs from "@/components/FullTabs.svelte";
  import CommitDetails from "./CommitDetails.svelte";
  import { detailPanelContainer } from "./detailPanel.css";
  import WorkingDirectory from "./WorkingDirectory.svelte";
  import { workingDirectory$ } from "./workingDirectoryState";
  import { map } from "rxjs";
  import { withDefault } from "@react-rxjs/core";
  import { setDiffDelta } from "../DiffView/diffViewState";
  import { componentEffect } from "@/lib/rxState";
  import { commitChange$ } from "../RepoGrid/activeCommit";

  let fullTabs: FullTabs;
  componentEffect(
    commitChange$.subscribe(() => fullTabs.selectOption("details"))
  );

  const hasChanges$ = workingDirectory$.pipeState(
    map(
      ({ staged_deltas, unstaged_deltas }) =>
        staged_deltas.length + unstaged_deltas.length > 0
    ),
    withDefault(false)
  );
</script>

<FullTabs
  class={detailPanelContainer}
  padHeader
  options={[
    {
      id: "details",
      header: "Commit Details",
    },
    {
      id: "workingDir",
      header: `Working Directory`,
      highlight: $hasChanges$,
    },
  ]}
  on:tabchange={(evt) => {
    if (evt.detail.id === "details") {
      setDiffDelta(null);
    }
  }}
  bind:this={fullTabs}
  let:id
>
  {#if id === "details"}
    <CommitDetails />
  {:else if id == "workingDir"}
    <WorkingDirectory />
  {/if}
</FullTabs>

<style>
</style>
